<a href="https://colab.research.google.com/github/mwidodo/machinelearningproject/blob/ANN/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Importing Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

Data processing

Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/My Drive/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


Encoding categorical data

Label encoding the "Gender Column"

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geograph" Column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into the Training set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Part 2: Building the ANN

Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

Adding the Input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the output layers

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

Training the ANN

Compiling the ANN, opti: perform stocstic gradient descent, it updates the weight to reduce the loss between the pred and actual.

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the ANN on the Training set batch size, epoch = learning through severl iterations

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7626
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4459 - accuracy: 0.7996
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4282 - accuracy: 0.8184
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4165 - accuracy: 0.8267
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4089 - accuracy: 0.8295
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4037 - accuracy: 0.8303
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3988 - accuracy: 0.8300
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3946 - accuracy: 0.8321
Epoch 10/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3912 - accura

Using ANN model to predict if the customer with the following information would leave the bank:
Geo: France
Credit Score: 600
Age: 40
Tenure: 3 years
Balance: 60000
Number of Products: 2
Have Credit Card: Yes
Active Member: Yes
Estimated Salary: 50000

Solution

In [ ]:
print(ann.predict(sc.transform([[1, 0 , 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 131ms/step
[[False]]


Our ANN model predicts that this customer stays in the bank